services:
  - type: web
    name: pulseops-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: https://pulseops-dashboard.onrender.com
      - key: FAILURE_THRESHOLD
        value: "3"
      - key: SUPABASE_URL
        value: https://kpfqzyejzcirlavewmqi.supabase.co
      - key: SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_JYksltCemRN_zuY8ASF1ug_i5p_wXPl

  - type: web
    name: pulseops-dashboard
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://kpfqzyejzcirlavewmqi.supabase.co
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_JYksltCemRN_zuY8ASF1ug_i5p_wXPl
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
